apiVersion: v1
kind: Pod
metadata:
  name: pod-container-probe
  labels:
    app: webapp
spec:
  containers:
    - name: pod-container-probe
      image: nginx
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
      livenessProbe:
        httpGet:
          port: 8080
          scheme: HTTP
        periodSeconds: 10
        initialDelaySeconds: 10
  restartPolicy: Never
